# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0

{{- $dcfg := .Config.Dockerfile }}

{{ range $dcfg.ExtraBuildStages -}}
{{ trimSpace . }}

################################################################################

{{ end -}}

FROM golang:{{ .Constants.DefaultGoVersion }}-alpine{{ .Constants.DefaultAlpineImage }} AS builder

RUN apk add --no-cache --no-progress ca-certificates gcc git make musl-dev {{- range $dcfg.ExtraBuildPackages }} {{.}}{{ end }}

COPY . /src
ARG BININFO_BUILD_DATE BININFO_COMMIT_HASH BININFO_VERSION # provided to 'make install'
RUN {{ if .UseBuildKit }}--mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
  {{ end }}make -C /src install PREFIX=/pkg GOTOOLCHAIN=local{{ if .Config.Golang.EnableVendoring }} GO_BUILDFLAGS='-mod vendor'{{ end }}

{{ range $dcfg.ExtraBuildDirectives -}}
{{ . }}
{{ end -}}

################################################################################

FROM alpine:{{ .Constants.DefaultAlpineImage }}

{{ if not $dcfg.RunAsRoot -}}
RUN addgroup -g 4200 appgroup \
  && adduser -h /home/appuser -s /sbin/nologin -G appgroup -D -u 4200 appuser

{{ end -}}
# upgrade all installed packages to fix potential CVEs in advance
# also remove apk package manager to hopefully remove dependency on OpenSSL 🤞
RUN {{ .RunCommands }}

COPY --from=builder /etc/ssl/certs/ /etc/ssl/certs/
COPY --from=builder /etc/ssl/cert.pem /etc/ssl/cert.pem
COPY --from=builder /pkg/ /usr/
# make sure all binaries can be executed
{{- if .RunVersionCommands }}
RUN set -x \
  && {{ .RunVersionCommands }}
{{- end }}

ARG BININFO_BUILD_DATE BININFO_COMMIT_HASH BININFO_VERSION
LABEL source_repository="{{ .Config.Metadata.URL }}" \
  org.opencontainers.image.url="{{ .Config.Metadata.URL }}" \
  org.opencontainers.image.created=${BININFO_BUILD_DATE} \
  org.opencontainers.image.revision=${BININFO_COMMIT_HASH} \
  org.opencontainers.image.version=${BININFO_VERSION}

{{ range $dcfg.ExtraDirectives -}}
{{ . }}
{{ end -}}
{{ if $dcfg.RunAsRoot -}}
WORKDIR /
{{ else -}}
USER 4200:4200
WORKDIR /home/appuser
{{ end -}}
ENTRYPOINT [ {{ .Entrypoint }} ]
