// SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0

package ghworkflow

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/sapcc/go-bits/logg"
	"github.com/sapcc/go-bits/must"
	. "go.xyrillian.de/gg/option"
	"go.yaml.in/yaml/v3"

	"github.com/sapcc/go-makefile-maker/internal/core"
	"github.com/sapcc/go-makefile-maker/internal/golang"
)

const workflowDir = ".github/workflows"

// Render renders GitHub workflows.
// Returns a list of filenames for all files that were generated.
func Render(cfg core.Configuration, sr golang.ScanResult) []string {
	ghwCfg := cfg.GitHubWorkflow

	must.Succeed(os.MkdirAll(workflowDir, 0o755))

	// remove renamed files
	must.Succeed(os.RemoveAll(filepath.Join(workflowDir, "codeql.yml")))
	must.Succeed(os.RemoveAll(filepath.Join(workflowDir, "dependency-review.yaml")))
	must.Succeed(os.RemoveAll(filepath.Join(workflowDir, "license.yaml")))
	must.Succeed(os.RemoveAll(filepath.Join(workflowDir, "spell.yaml")))

	// TODO: checking on GoVersion is only an aid until we can properly detect rust applications
	var allWorkflows []Option[workflow]
	if sr.GoVersion != "" {
		allWorkflows = append(allWorkflows, checksWorkflow(cfg))
		allWorkflows = append(allWorkflows, ciWorkflow(cfg, sr))
		allWorkflows = append(allWorkflows, codeQLWorkflow(cfg))
	}
	allWorkflows = append(allWorkflows, helmWorkflow(cfg))
	allWorkflows = append(allWorkflows, ghcrWorkflow(ghwCfg))
	allWorkflows = append(allWorkflows, releaseWorkflow(cfg))

	var result []string
	for _, workflowOrNone := range allWorkflows {
		w, ok := workflowOrNone.Unpack()
		if ok {
			writeWorkflowToFile(w)
			result = append(result, w.getPath())
		}
	}
	return result
}

func writeWorkflowToFile(w workflow) {
	path := w.getPath()
	logg.Debug("-> writing file %s", path)
	f := must.Return(os.Create(path))
	defer f.Close()

	encoder := yaml.NewEncoder(f)
	defer encoder.Close()
	encoder.SetIndent(2)

	fmt.Fprintln(f, core.AutogeneratedHeader)
	must.Succeed(encoder.Encode(w))
}
